# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4106bfb4b2e9cca2ec2f41d7bb5752378df355ea3a0dc049d57f0fc2817a974fc2a7fa0b88c9f86b7f89eb36ffe00b8135e6f97d6e191c0b2914331015ae6a8

test:
  secret_key_base: 84fc2731618f9c4871f5d8286addad3c6984dcbef955b217d1604bd46f7336c7f7106d8846f955624bd3279ce80bf9553fa706d820ab1b4cba3fb9f92e1d3453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
